version: "3.1"

services:
  app:
    build: .
    # image: node:16.19.1-alpine
    container_name: api
    command: npm run dev
    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - $PWD:/api
  db:
    image: mysql
    container_name: mysql-api
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # ports:
      # - 3306:3306
    # volumes:
      # - $PWD/data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
    - 8088:8080
    