version: "3.1"

services:
  mysqldb:
    image: mysql
    container_name: mysql-api
    command: 
      --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: base_de_dados
      # MYSQL_USER: usuario
      # MYSQL_PASSWORD: senha
      MYSQL_ROOT_HOST: '%'
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      # - data:/var/lib/mysql:rw
      # - '$PWD/data:/var/lib/mysql'
      - "./create-db-template.sql:/docker-entrypoint-initdb.d/1.sql"
    # user: mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
    - 8088:8080
  app:
    build: .
    restart: unless-stopped
    # image: node:16.19.1-alpine
    container_name: api
    command: npm run dev
    ports:
      - 3333:3333
    environment:
      - DB_HOST=mysqldb
    depends_on:
      - mysqldb
    volumes:
      - $PWD:/api
volumes:
  data:
